# Generated by Django 3.2.3 on 2021-08-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('certificate', 'Certificate'), ('award', 'Award')], default='certificate', max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('firm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Master')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile_name', models.CharField(max_length=150)),
                ('profile_title', models.CharField(max_length=150)),
                ('profile_biography', models.CharField(max_length=220)),
                ('profile_location', models.CharField(max_length=50)),
                ('profile_color', models.CharField(choices=[('primary', 'Blue'), ('danger', 'Red'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Cyan'), ('secondary', 'Grey')], default='primary', max_length=20)),
            ],
        ),
    ]
