# Generated by Django 3.2.3 on 2021-08-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certificate_experience_hobby_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_biography',
            field=models.TextField(max_length=220),
        ),
    ]
