# Generated by Django 3.2.3 on 2021-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211014_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Native')], default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1),
        ),
    ]
