# Generated by Django 3.2.3 on 2021-10-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
