# Generated by Django 3.2.3 on 2021-10-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
    ]
