# Generated by Django 3.2.3 on 2021-10-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211016_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='deafuılt', max_length=50),
            preserve_default=False,
        ),
    ]
