# Generated by Django 3.2.3 on 2021-10-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_biography',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_title',
            new_name='title',
        ),
    ]
