# Generated by Django 3.2.3 on 2021-10-17 01:14

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211017_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=main.models.photo_path),
        ),
    ]
