# Generated by Django 3.2.3 on 2021-10-17 01:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(storage=main.models.OverwriteStorage(), upload_to=main.models.photo_path),
        ),
    ]
