# Generated by Django 3.2.3 on 2021-10-17 02:07

from django.db import migrations
import django_resized.forms
import main.models
import portfolio.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], storage=portfolio.storage.OverwriteStorage(), upload_to=main.models.photo_path),
        ),
    ]
